### ISSUE TITLE
Missing LICENSE and COPYRIGHT files

### ISSUE THREAD

**Issue by ralphlange** [epics-base/normativeTypesCPP#1]
*From Andrew Johnson &lt;anj_AT_aps.anl.gov&gt;:*

Module is missing LICENSE and COPYRIGHT files which are referred to in source code header comments within the module

**Comment by anjohnson** [comment]
I have added the LICENSE file in my branch of normativeTypesCPP, but I'm not sure who should be listed in the COPYRIGHT file. I'm seeing commits in the git log from David, Matej, Marty, Guobao and Ralph. David, I don't see any Diamond copyrights given in the other module COPYRIGHT files, can you advise what to do please.

**Comment by dhickin** [comment]
Our code has a mixture of "(C) Diamond Light Source" and "(C) Diamond Light Source Ltd." as does our website. Either's probably OK, but our "Legal Notice" page uses the latter so I suggest you use that.

**Comment by dhickin** [comment]
Fixed by b976d918d572b12c0a4be3030b49857683fd0429
