### ISSUE TITLE
NTNDArrayAttributeBuilder's tags field is not being properly reset

### ISSUE THREAD

**Issue by brunoseivam** [epics-base/normativeTypesCPP#11]
`NTNDArrayAttributeBuilder`'s `tags` field is being ignored inside the `reset` method. This is causing generated `NTNDArrayAttribute`'s to randomly contain or not the `tags` field, triggering epics-base/pvAccessCPP#40 issue for me.

**Comment by mdavidsaver** [comment]
#12 fixes clear bug, although I don't see how this triggers epics-base/pvAccessCPP#40.  I'll have to investigate this further.

**Comment by brunoseivam** [comment]
[This](https://gist.github.com/brunoseivam/ce07a672e40e485a8eafdff2142b5425) triggers what I was seeing. 

Now that I am thinking about it, the issue in this snippet seems to be that I am `put`ting a PVStructure that is different than the one advertised. 

This was happening inadvertently then the `tags` field was being erroneously and silently added.

**Comment by mdavidsaver** [comment]
Ok, that makes some sense.  In my mind "Not-a-first segmented message expected" equates to a (de)serialization error.  Right now there is not a lot of protection against this kind of error and more needs to be added.

At the same time, I don't think that building new types so frequently is such a good idea.  To me this is an initialization activity for a server.
